INSERT INTO countries (country_name, country_code3, country_code, currency, currency_name, currency_symbol) VALUES
('Afghanistan', 'AFG', 'AF', 'AFN', 'Afghan afghani', '؋'),
('Aland Islands', 'ALA', 'AX', 'EUR', 'Euro', '€'),
('Albania', 'ALB', 'AL', 'ALL', 'Albanian lek', 'Lek'),
('Algeria', 'DZA', 'DZ', 'DZD', 'Algerian dinar', 'دج'),
('American Samoa', 'ASM', 'AS', 'USD', 'US Dollar', '$'),
('Andorra', 'AND', 'AD', 'EUR', 'Euro', '€'),
('Angola', 'AGO', 'AO', 'AOA', 'Angolan kwanza', 'Kz'),
('Anguilla', 'AIA', 'AI', 'XCD', 'East Caribbean dollar', '$'),
('Antarctica', 'ATA', 'AQ', 'AAD', 'Antarctican dollar', '$'),
('Antigua And Barbuda', 'ATG', 'AG', 'XCD', 'Eastern Caribbean dollar', '$'),
('Argentina', 'ARG', 'AR', 'ARS', 'Argentine peso', '$'),
('Armenia', 'ARM', 'AM', 'AMD', 'Armenian dram', '֏'),
('Aruba', 'ABW', 'AW', 'AWG', 'Aruban florin', 'ƒ'),
('Australia', 'AUS', 'AU', 'AUD', 'Australian dollar', '$'),
('Austria', 'AUT', 'AT', 'EUR', 'Euro', '€'),
('Azerbaijan', 'AZE', 'AZ', 'AZN', 'Azerbaijani manat', 'm'),
('The Bahamas', 'BHS', 'BS', 'BSD', 'Bahamian dollar', 'B$'),
('Bahrain', 'BHR', 'BH', 'BHD', 'Bahraini dinar', '.د.ب'),
('Bangladesh', 'BGD', 'BD', 'BDT', 'Bangladeshi taka', '৳'),
('Barbados', 'BRB', 'BB', 'BBD', 'Barbadian dollar', 'Bds$'),
('Belarus', 'BLR', 'BY', 'BYN', 'Belarusian ruble', 'Br'),
('Belgium', 'BEL', 'BE', 'EUR', 'Euro', '€'),
('Belize', 'BLZ', 'BZ', 'BZD', 'Belize dollar', '$'),
('Benin', 'BEN', 'BJ', 'XOF', 'West African CFA franc', 'CFA'),
('Bermuda', 'BMU', 'BM', 'BMD', 'Bermudian dollar', '$'),
('Bhutan', 'BTN', 'BT', 'BTN', 'Bhutanese ngultrum', 'Nu.'),
('Bolivia', 'BOL', 'BO', 'BOB', 'Bolivian boliviano', 'Bs.'),
('Bosnia and Herzegovina', 'BIH', 'BA', 'BAM', 'Bosnia and Herzegovina convertible mark', 'KM'),
('Botswana', 'BWA', 'BW', 'BWP', 'Botswana pula', 'P'),
('Bouvet Island', 'BVT', 'BV', 'NOK', 'Norwegian Krone', 'kr'),
('Brazil', 'BRA', 'BR', 'BRL', 'Brazilian real', 'R$'),
('British Indian Ocean Territory', 'IOT', 'IO', 'USD', 'United States dollar', '$'),
('Brunei', 'BRN', 'BN', 'BND', 'Brunei dollar', 'B$'),
('Bulgaria', 'BGR', 'BG', 'BGN', 'Bulgarian lev', 'Лв.'),
('Burkina Faso', 'BFA', 'BF', 'XOF', 'West African CFA franc', 'CFA'),
('Burundi', 'BDI', 'BI', 'BIF', 'Burundian franc', 'FBu'),
('Cambodia', 'KHM', 'KH', 'KHR', 'Cambodian riel', 'KHR'),
('Cameroon', 'CMR', 'CM', 'XAF', 'Central African CFA franc', 'FCFA'),
('Canada', 'CAN', 'CA', 'CAD', 'Canadian dollar', '$'),
('Cape Verde', 'CPV', 'CV', 'CVE', 'Cape Verdean escudo', '$'),
('Cayman Islands', 'CYM', 'KY', 'KYD', 'Cayman Islands dollar', '$'),
('Central African Republic', 'CAF', 'CF', 'XAF', 'Central African CFA franc', 'FCFA'),
('Chad', 'TCD', 'TD', 'XAF', 'Central African CFA franc', 'FCFA'),
('Chile', 'CHL', 'CL', 'CLP', 'Chilean peso', '$'),
('China', 'CHN', 'CN', 'CNY', 'Chinese yuan', '¥'),
('Christmas Island', 'CXR', 'CX', 'AUD', 'Australian dollar', '$'),
('Cocos (Keeling) Islands', 'CCK', 'CC', 'AUD', 'Australian dollar', '$'),
('Colombia', 'COL', 'CO', 'COP', 'Colombian peso', '$'),
('Comoros', 'COM', 'KM', 'KMF', 'Comorian franc', 'CF'),
('Congo', 'COG', 'CG', 'XAF', 'Central African CFA franc', 'FC'),
('Democratic Republic of the Congo', 'COD', 'CD', 'CDF', 'Congolese Franc', 'FC'),
('Cook Islands', 'COK', 'CK', 'NZD', 'Cook Islands dollar', '$'),
('Costa Rica', 'CRI', 'CR', 'CRC', 'Costa Rican colón', '₡'),
('Cote D\Ivoire (Ivory Coast)', 'CIV', 'CI', 'XOF', 'West African CFA franc', 'CFA'),
('Croatia', 'HRV', 'HR', 'HRK', 'Croatian kuna', 'kn'),
('Cuba', 'CUB', 'CU', 'CUP', 'Cuban peso', '$'),
('Cyprus', 'CYP', 'CY', 'EUR', 'Euro', '€'),
('Czech Republic', 'CZE', 'CZ', 'CZK', 'Czech koruna', 'Kč'),
('Denmark', 'DNK', 'DK', 'DKK', 'Danish krone', 'Kr.'),
('Djibouti', 'DJI', 'DJ', 'DJF', 'Djiboutian franc', 'Fdj'),
('Dominica', 'DMA', 'DM', 'XCD', 'Eastern Caribbean dollar', '$'),
('Dominican Republic', 'DOM', 'DO', 'DOP', 'Dominican peso', '$'),
('East Timor', 'TLS', 'TL', 'USD', 'United States dollar', '$'),
('Ecuador', 'ECU', 'EC', 'USD', 'United States dollar', '$'),
('Egypt', 'EGY', 'EG', 'EGP', 'Egyptian pound', 'ج.م'),
('El Salvador', 'SLV', 'SV', 'USD', 'United States dollar', '$'),
('Equatorial Guinea', 'GNQ', 'GQ', 'XAF', 'Central African CFA franc', 'FCFA'),
('Eritrea', 'ERI', 'ER', 'ERN', 'Eritrean nakfa', 'Nfk'),
('Estonia', 'EST', 'EE', 'EUR', 'Euro', '€'),
('Ethiopia', 'ETH', 'ET', 'ETB', 'Ethiopian birr', 'Nkf'),
('Falkland Islands', 'FLK', 'FK', 'FKP', 'Falkland Islands pound', '£'),
('Faroe Islands', 'FRO', 'FO', 'DKK', 'Danish krone', 'Kr.'),
('Fiji Islands', 'FJI', 'FJ', 'FJD', 'Fijian dollar', 'FJ$'),
('Finland', 'FIN', 'FI', 'EUR', 'Euro', '€'),
('France', 'FRA', 'FR', 'EUR', 'Euro', '€'),
('French Guiana', 'GUF', 'GF', 'EUR', 'Euro', '€'),
('French Polynesia', 'PYF', 'PF', 'XPF', 'CFP franc', '₣'),
('French Southern Territories', 'ATF', 'TF', 'EUR', 'Euro', '€'),
('Gabon', 'GAB', 'GA', 'XAF', 'Central African CFA franc', 'FCFA'),
('Gambia The', 'GMB', 'GM', 'GMD', 'Gambian dalasi', 'D'),
('Georgia', 'GEO', 'GE', 'GEL', 'Georgian lari', 'ლ'),
('Germany', 'DEU', 'DE', 'EUR', 'Euro', '€'),
('Ghana', 'GHA', 'GH', 'GHS', 'Ghanaian cedi', 'GH₵'),
('Gibraltar', 'GIB', 'GI', 'GIP', 'Gibraltar pound', '£'),
('Greece', 'GRC', 'GR', 'EUR', 'Euro', '€'),
('Greenland', 'GRL', 'GL', 'DKK', 'Danish krone', 'Kr.'),
('Grenada', 'GRD', 'GD', 'XCD', 'Eastern Caribbean dollar', '$'),
('Guadeloupe', 'GLP', 'GP', 'EUR', 'Euro', '€'),
('Guam', 'GUM', 'GU', 'USD', 'US Dollar', '$'),
('Guatemala', 'GTM', 'GT', 'GTQ', 'Guatemalan quetzal', 'Q'),
('Guernsey and Alderney', 'GGY', 'GG', 'GBP', 'British pound', '£'),
('Guinea', 'GIN', 'GN', 'GNF', 'Guinean franc', 'FG'),
('Guinea-Bissau', 'GNB', 'GW', 'XOF', 'West African CFA franc', 'CFA'),
('Guyana', 'GUY', 'GY', 'GYD', 'Guyanese dollar', '$'),
('Haiti', 'HTI', 'HT', 'HTG', 'Haitian gourde', 'G'),
('Heard Island and McDonald Islands', 'HMD', 'HM', 'AUD', 'Australian dollar', '$'),
('Honduras', 'HND', 'HN', 'HNL', 'Honduran lempira', 'L'),
('Hong Kong S.A.R.', 'HKG', 'HK', 'HKD', 'Hong Kong dollar', '$'),
('Hungary', 'HUN', 'HU', 'HUF', 'Hungarian forint', 'Ft'),
('Iceland', 'ISL', 'IS', 'ISK', 'Icelandic króna', 'kr'),
('India', 'IND', 'IN', 'INR', 'Indian rupee', '₹'),
('Indonesia', 'IDN', 'ID', 'IDR', 'Indonesian rupiah', 'Rp'),
('Iran', 'IRN', 'IR', 'IRR', 'Iranian rial', '﷼'),
('Iraq', 'IRQ', 'IQ', 'IQD', 'Iraqi dinar', 'د.ع'),
('Ireland', 'IRL', 'IE', 'EUR', 'Euro', '€'),
('Israel', 'ISR', 'IL', 'ILS', 'Israeli new shekel', '₪'),
('Italy', 'ITA', 'IT', 'EUR', 'Euro', '€'),
('Jamaica', 'JAM', 'JM', 'JMD', 'Jamaican dollar', 'J$'),
('Japan', 'JPN', 'JP', 'JPY', 'Japanese yen', '¥'),
('Jersey', 'JEY', 'JE', 'GBP', 'British pound', '£'),
('Jordan', 'JOR', 'JO', 'JOD', 'Jordanian dinar', 'ا.د'),
('Kazakhstan', 'KAZ', 'KZ', 'KZT', 'Kazakhstani tenge', 'лв'),
('Kenya', 'KEN', 'KE', 'KES', 'Kenyan shilling', 'KSh'),
('Kiribati', 'KIR', 'KI', 'AUD', 'Australian dollar', '$'),
('North Korea', 'PRK', 'KP', 'KPW', 'North Korean Won', '₩'),
('South Korea', 'KOR', 'KR', 'KRW', 'Won', '₩'),
('Kuwait', 'KWT', 'KW', 'KWD', 'Kuwaiti dinar', 'ك.د'),
('Kyrgyzstan', 'KGZ', 'KG', 'KGS', 'Kyrgyzstani som', 'лв'),
('Laos', 'LAO', 'LA', 'LAK', 'Lao kip', '₭'),
('Latvia', 'LVA', 'LV', 'EUR', 'Euro', '€'),
('Lebanon', 'LBN', 'LB', 'LBP', 'Lebanese pound', '£'),
('Lesotho', 'LSO', 'LS', 'LSL', 'Lesotho loti', 'L'),
('Liberia', 'LBR', 'LR', 'LRD', 'Liberian dollar', '$'),
('Libya', 'LBY', 'LY', 'LYD', 'Libyan dinar', 'د.ل'),
('Liechtenstein', 'LIE', 'LI', 'CHF', 'Swiss franc', 'CHf'),
('Lithuania', 'LTU', 'LT', 'EUR', 'Euro', '€'),
('Luxembourg', 'LUX', 'LU', 'EUR', 'Euro', '€'),
('Macau S.A.R.', 'MAC', 'MO', 'MOP', 'Macanese pataca', '$'),
('Macedonia', 'MKD', 'MK', 'MKD', 'Denar', 'ден'),
('Madagascar', 'MDG', 'MG', 'MGA', 'Malagasy ariary', 'Ar'),
('Malawi', 'MWI', 'MW', 'MWK', 'Malawian kwacha', 'MK'),
('Malaysia', 'MYS', 'MY', 'MYR', 'Malaysian ringgit', 'RM'),
('Maldives', 'MDV', 'MV', 'MVR', 'Maldivian rufiyaa', 'Rf'),
('Mali', 'MLI', 'ML', 'XOF', 'West African CFA franc', 'CFA'),
('Malta', 'MLT', 'MT', 'EUR', 'Euro', '€'),
('Man (Isle of)', 'IMN', 'IM', 'GBP', 'British pound', '£'),
('Marshall Islands', 'MHL', 'MH', 'USD', 'United States dollar', '$'),
('Martinique', 'MTQ', 'MQ', 'EUR', 'Euro', '€'),
('Mauritania', 'MRT', 'MR', 'MRO', 'Mauritanian ouguiya', 'MRU'),
('Mauritius', 'MUS', 'MU', 'MUR', 'Mauritian rupee', '₨'),
('Mayotte', 'MYT', 'YT', 'EUR', 'Euro', '€'),
('Mexico', 'MEX', 'MX', 'MXN', 'Mexican peso', '$'),
('Micronesia', 'FSM', 'FM', 'USD', 'United States dollar', '$'),
('Moldova', 'MDA', 'MD', 'MDL', 'Moldovan leu', 'L'),
('Monaco', 'MCO', 'MC', 'EUR', 'Euro', '€'),
('Mongolia', 'MNG', 'MN', 'MNT', 'Mongolian tögrög', '₮'),
('Montenegro', 'MNE', 'ME', 'EUR', 'Euro', '€'),
('Montserrat', 'MSR', 'MS', 'XCD', 'Eastern Caribbean dollar', '$'),
('Morocco', 'MAR', 'MA', 'MAD', 'Moroccan dirham', 'DH'),
('Mozambique', 'MOZ', 'MZ', 'MZN', 'Mozambican metical', 'MT'),
('Myanmar', 'MMR', 'MM', 'MMK', 'Burmese kyat', 'K'),
('Namibia', 'NAM', 'NA', 'NAD', 'Namibian dollar', '$'),
('Nauru', 'NRU', 'NR', 'AUD', 'Australian dollar', '$'),
('Nepal', 'NPL', 'NP', 'NPR', 'Nepalese rupee', '₨'),
('Bonaire, Sint Eustatius and Saba', 'BES', 'BQ', 'USD', 'United States dollar', '$'),
('Netherlands', 'NLD', 'NL', 'EUR', 'Euro', '€'),
('New Caledonia', 'NCL', 'NC', 'XPF', 'CFP franc', '₣'),
('New Zealand', 'NZL', 'NZ', 'NZD', 'New Zealand dollar', '$'),
('Nicaragua', 'NIC', 'NI', 'NIO', 'Nicaraguan córdoba', 'C$'),
('Niger', 'NER', 'NE', 'XOF', 'West African CFA franc', 'CFA'),
('Nigeria', 'NGA', 'NG', 'NGN', 'Nigerian naira', '₦'),
('Niue', 'NIU', 'NU', 'NZD', 'New Zealand dollar', '$'),
('Norfolk Island', 'NFK', 'NF', 'AUD', 'Australian dollar', '$'),
('Northern Mariana Islands', 'MNP', 'MP', 'USD', 'United States dollar', '$'),
('Norway', 'NOR', 'NO', 'NOK', 'Norwegian krone', 'kr'),
('Oman', 'OMN', 'OM', 'OMR', 'Omani rial', '.ع.ر'),
('Pakistan', 'PAK', 'PK', 'PKR', 'Pakistani rupee', '₨'),
('Palau', 'PLW', 'PW', 'USD', 'United States dollar', '$'),
('Palestinian Territory Occupied', 'PSE', 'PS', 'ILS', 'Israeli new shekel', '₪'),
('Panama', 'PAN', 'PA', 'PAB', 'Panamanian balboa', 'B/.'),
('Papua new Guinea', 'PNG', 'PG', 'PGK', 'Papua New Guinean kina', 'K'),
('Paraguay', 'PRY', 'PY', 'PYG', 'Paraguayan guarani', '₲'),
('Peru', 'PER', 'PE', 'PEN', 'Peruvian sol', 'S/.'),
('Philippines', 'PHL', 'PH', 'PHP', 'Philippine peso', '₱'),
('Pitcairn Island', 'PCN', 'PN', 'NZD', 'New Zealand dollar', '$'),
('Poland', 'POL', 'PL', 'PLN', 'Polish złoty', 'zł'),
('Portugal', 'PRT', 'PT', 'EUR', 'Euro', '€'),
('Puerto Rico', 'PRI', 'PR', 'USD', 'United States dollar', '$'),
('Qatar', 'QAT', 'QA', 'QAR', 'Qatari riyal', 'ق.ر'),
('Reunion', 'REU', 'RE', 'EUR', 'Euro', '€'),
('Romania', 'ROU', 'RO', 'RON', 'Romanian leu', 'lei'),
('Russia', 'RUS', 'RU', 'RUB', 'Russian ruble', '₽'),
('Rwanda', 'RWA', 'RW', 'RWF', 'Rwandan franc', 'FRw'),
('Saint Helena', 'SHN', 'SH', 'SHP', 'Saint Helena pound', '£'),
('Saint Kitts And Nevis', 'KNA', 'KN', 'XCD', 'Eastern Caribbean dollar', '$'),
('Saint Lucia', 'LCA', 'LC', 'XCD', 'Eastern Caribbean dollar', '$'),
('Saint Pierre and Miquelon', 'SPM', 'PM', 'EUR', 'Euro', '€'),
('Saint Vincent And The Grenadines', 'VCT', 'VC', 'XCD', 'Eastern Caribbean dollar', '$'),
('Saint-Barthelemy', 'BLM', 'BL', 'EUR', 'Euro', '€'),
('Saint-Martin (French part)', 'MAF', 'MF', 'EUR', 'Euro', '€'),
('Samoa', 'WSM', 'WS', 'WST', 'Samoan tālā', 'SAT'),
('San Marino', 'SMR', 'SM', 'EUR', 'Euro', '€'),
('Sao Tome and Principe', 'STP', 'ST', 'STD', 'Dobra', 'Db'),
('Saudi Arabia', 'SAU', 'SA', 'SAR', 'Saudi riyal', '﷼'),
('Senegal', 'SEN', 'SN', 'XOF', 'West African CFA franc', 'CFA'),
('Serbia', 'SRB', 'RS', 'RSD', 'Serbian dinar', 'din'),
('Seychelles', 'SYC', 'SC', 'SCR', 'Seychellois rupee', 'SRe'),
('Sierra Leone', 'SLE', 'SL', 'SLL', 'Sierra Leonean leone', 'Le'),
('Singapore', 'SGP', 'SG', 'SGD', 'Singapore dollar', '$'),
('Slovakia', 'SVK', 'SK', 'EUR', 'Euro', '€'),
('Slovenia', 'SVN', 'SI', 'EUR', 'Euro', '€'),
('Solomon Islands', 'SLB', 'SB', 'SBD', 'Solomon Islands dollar', 'Si$'),
('Somalia', 'SOM', 'SO', 'SOS', 'Somali shilling', 'Sh.so.'),
('South Africa', 'ZAF', 'ZA', 'ZAR', 'South African rand', 'R'),
('South Georgia', 'SGS', 'GS', 'GBP', 'British pound', '£'),
('South Sudan', 'SSD', 'SS', 'SSP', 'South Sudanese pound', '£'),
('Spain', 'ESP', 'ES', 'EUR', 'Euro', '€'),
('Sri Lanka', 'LKA', 'LK', 'LKR', 'Sri Lankan rupee', 'Rs'),
('Sudan', 'SDN', 'SD', 'SDG', 'Sudanese pound', '.س.ج'),
('Suriname', 'SUR', 'SR', 'SRD', 'Surinamese dollar', '$'),
('Svalbard And Jan Mayen Islands', 'SJM', 'SJ', 'NOK', 'Norwegian Krone', 'kr'),
('Swaziland', 'SWZ', 'SZ', 'SZL', 'Lilangeni', 'E'),
('Sweden', 'SWE', 'SE', 'SEK', 'Swedish krona', 'kr'),
('Switzerland', 'CHE', 'CH', 'CHF', 'Swiss franc', 'CHf'),
('Syria', 'SYR', 'SY', 'SYP', 'Syrian pound', 'LS'),
('Taiwan', 'TWN', 'TW', 'TWD', 'New Taiwan dollar', '$'),
('Tajikistan', 'TJK', 'TJ', 'TJS', 'Tajikistani somoni', 'SM'),
('Tanzania', 'TZA', 'TZ', 'TZS', 'Tanzanian shilling', 'TSh'),
('Thailand', 'THA', 'TH', 'THB', 'Thai baht', '฿'),
('Togo', 'TGO', 'TG', 'XOF', 'West African CFA franc', 'CFA'),
('Tokelau', 'TKL', 'TK', 'NZD', 'New Zealand dollar', '$'),
('Tonga', 'TON', 'TO', 'TOP', 'Tongan paʻanga', '$'),
('Trinidad And Tobago', 'TTO', 'TT', 'TTD', 'Trinidad and Tobago dollar', '$'),
('Tunisia', 'TUN', 'TN', 'TND', 'Tunisian dinar', 'ت.د'),
('Turkey', 'TUR', 'TR', 'TRY', 'Turkish lira', '₺'),
('Turkmenistan', 'TKM', 'TM', 'TMT', 'Turkmenistan manat', 'T'),
('Turks And Caicos Islands', 'TCA', 'TC', 'USD', 'United States dollar', '$'),
('Tuvalu', 'TUV', 'TV', 'AUD', 'Australian dollar', '$'),
('Uganda', 'UGA', 'UG', 'UGX', 'Ugandan shilling', 'USh'),
('Ukraine', 'UKR', 'UA', 'UAH', 'Ukrainian hryvnia', '₴'),
('United Arab Emirates', 'ARE', 'AE', 'AED', 'United Arab Emirates dirham', 'إ.د'),
('United Kingdom', 'GBR', 'GB', 'GBP', 'British pound', '£'),
('United States', 'USA', 'US', 'USD', 'United States dollar', '$'),
('United States Minor Outlying Islands', 'UMI', 'UM', 'USD', 'United States dollar', '$'),
('Uruguay', 'URY', 'UY', 'UYU', 'Uruguayan peso', '$'),
('Uzbekistan', 'UZB', 'UZ', 'UZS', 'Uzbekistani soʻm', 'лв'),
('Vanuatu', 'VUT', 'VU', 'VUV', 'Vanuatu vatu', 'VT'),
('Vatican City State (Holy See)', 'VAT', 'VA', 'EUR', 'Euro', '€'),
('Venezuela', 'VEN', 'VE', 'VEF', 'Bolívar', 'Bs'),
('Vietnam', 'VNM', 'VN', 'VND', 'Vietnamese đồng', '₫'),
('Virgin Islands (British)', 'VGB', 'VG', 'USD', 'United States dollar', '$'),
('Virgin Islands (US)', 'VIR', 'VI', 'USD', 'United States dollar', '$'),
('Wallis And Futuna Islands', 'WLF', 'WF', 'XPF', 'CFP franc', '₣'),
('Western Sahara', 'ESH', 'EH', 'MAD', 'Moroccan Dirham', 'MAD'),
('Yemen', 'YEM', 'YE', 'YER', 'Yemeni rial', '﷼'),
('Zambia', 'ZMB', 'ZM', 'ZMW', 'Zambian kwacha', 'ZK'),
('Zimbabwe', 'ZWE', 'ZW', 'ZWL', 'Zimbabwe Dollar', '$'),
('Kosovo', 'XKX', 'XK', 'EUR', 'Euro', '€'),
('Curaçao', 'CUW', 'CW', 'ANG', 'Netherlands Antillean guilder', 'ƒ'),
('Sint Maarten (Dutch part)', 'SXM', 'SX', 'ANG', 'Netherlands Antillean guilder', 'ƒ');